action: "create" # destroy, can passed also to CLI with --action
registry_config_file: !ENV "${HOME}/registry-config.json"
parallel: True
clusters_install_data_directory: "/tmp/clusters-data"
s3_bucket_name: "openshift-cli-installer"
s3_bucket_path: "openshift-ci"
ocm_token: !ENV "${OCM_TOKEN}"
ssh_key_file: !ENV "${HOME}/.ssh/id_rsa.pub"
docker_config_file: !ENV "${HOME}/.docker/config.json"
aws_access_key_id: !ENV "${AWS_ACCESS_KEY}"
aws_secret_access_key: !ENV "${AWS_SECRET_ACCESS_KEY}"
aws_account_id: !ENV "${AWS_ACCOUNT_ID}"
gcp_service_account_file: !ENV "${HOME}/gcp-service-account.json"

clusters:
# AWS OSD cluster
- name: aws-osd-c1
  platform: aws-osd
  region: us-east-2
  version: "4.13"
  channel-group: stable
  compute-machine-type: m5.4xlarge
  timeout: 90m
  replicas: 2
  fips: True
  ocm-env: stage
  expiration-time: 1h

# GCP OSD cluster
- name: gcp-osd-c1
  platform: gcp-osd
  region: us-east1
  version: "4.13"
  channel-group: stable
  compute-machine-type: custom-4-16384
  timeout: 90m
  replicas: 2
  fips: True
  ocm-env: stage
  expiration-time: 1h

# Rosa cluster with ACM deployed and attach `rosa-c2` cluster to the ACM hub
- name: rosa-c1
  platform: rosa
  region: us-east-2
  version: "4.13"
  channel-group: stable
  compute-machine-type: m5.4xlarge
  timeout: 90m
  replicas: 2
  fips: True
  ocm-env: stage
  acm: True
  acm-clusters:
    - name: rosa-c2
      platform: rosa

# Rosa cluster (Will be attahced to `rosa-c1` ACM hub)
- name: rosa-c2
  platform: rosa
  region: us-east-2
  version: "4.13"
  channel-group: stable
  compute-machine-type: m5.4xlarge
  timeout: 90m
  replicas: 2
  fips: True
  ocm-env: stage

# Hypershift cluster
- name: hyper-c1
  platform: hypershift
  region: us-west-2
  version: "4.13"
  channel-group: stable
  compute-machine-type: m5.4xlarge
  timeout: 90m
  replicas: 2
  ocm-env: stage
  expiration-time: 1h
  private_subnets:
    - 10.0.1.0/24
    - 10.0.2.0/24
  public_subnets:
    - 10.0.101.0/24
    - 10.0.102.0/24
  cidr: 10.0.0.0/16

# AWS IPI cluster
- name: aws-ipi-c1
  base_domain: aws.domain.example.com
  platform: aws
  region: us-east-2
  version: "4.13"
  stream: stable
  timeout: 1h
  worker_replicas: 2
  worker_flavor: m5.4xlarge
  worker_root_disk_size: 128
